# Generated by Django 2.1.5 on 2019-01-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaAna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=10, verbose_name='Data Criação')),
                ('tipo_despesa', models.CharField(choices=[('', (('1', 'Remédio'), ('2', 'Roupas'), ('3', 'Alimentação'), ('4', 'Educação'), ('5', 'Transporte'), ('6', 'Outros')))], default=' ', max_length=100, verbose_name='Tipo do Gasto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('forma_pagamento', models.CharField(choices=[(' ', (('A', 'Dinheiro'), ('B', 'Cartão de Crédito'), ('C', 'Cartão de Débito'), ('D', 'Cartão Crediário'), ('E', 'Cheque')))], default=' ', max_length=50, verbose_name='Forma Pagamento')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('quitado', models.BooleanField(verbose_name='Quitado')),
            ],
            options={
                'ordering': ('vencimento', '-forma_pagamento'),
            },
        ),
    ]
